### PR TITLE
Added possibility for authentication in case the mqtt broker requires it

### PR DESCRIPTION
**Pull request by ChrisKoh83**

### CODE REVIEW

**Comment by roscoe81** [comment]
Hi @ChrisKoh83 

Many thanks for doing this, it adds a lot of value. One thing you might like to add is a check of the config file for the new parameters - a bit like I have done in lines 102, 106 and 110. That will ensure backwards compatibility with older versions of the config file. Don't worry if you don't have time, I'm doing a few other code enhancements and I can add your PR, the config check and my enhancements as part of a new release. Thanks again and I trust that you're enjoying the project.

**Comment by ChrisKoh83** [comment]
> Hi @ChrisKoh83
> 
> Many thanks for doing this, it adds a lot of value. One thing you might like to add is a check of the config file for the new parameters - a bit like I have done in lines 102, 106 and 110. That will ensure backwards compatibility with older versions of the config file. Don't worry if you don't have time, I'm doing a few other code enhancements and I can add your PR, the config check and my enhancements as part of a new release. Thanks again and I trust that you're enjoying the project.

Hi @roscoe81 

you are welcome! I try to implement this within the next week.
Yes, that's a very cool project! I bought the enviro+ pHat months ago and finally I found some time to set it up.

greetings from Germany!
Chris

**Comment by roscoe81** [comment]
@ChrisKoh83 I've now added mqtt user name and password support as part of Version 5.23. I haven't tested it, so you might like to do so if you have a chance

**Comment by ChrisKoh83** [comment]
Thank you and sorry, I wasn't able to find some time to change my pull request so far!

I am now pulling your changes and try it out.

**Pull request closed without merging**
